### ISSUE TITLE
Cannot install on MacOS (Checking OPENSSL: no)

### ISSUE THREAD

**Issue by wchengk09** [rayylee/mwget#3]
I tried to install mwget on MacOS, but I got an error when configuring:
`Checking OPENSSL: no`
Then I installed OpenSSL:
`brew install openssl`
But it still outputs `Checking OPENSSL: no`. How to solve this problem?

**Comment by hburaylee** [comment]
Maybe openssl-devel needs to be installed instead of openssl.

**Comment by wchengk09** [comment]
Sorry, it doesn't work. I installed all the ssl packages, but it still doesn't work.

**Comment by wchengk09** [comment]
Maybe mwget does not support MacOS.

**Comment by hburaylee** [comment]
Currently, mwget has been refactored using Rust, so you can try the new version.
@wchengk09
